FROM abihf/android-sdk-base
MAINTAINER Abi Hafshin <abi@hafs.in>

RUN echo "y" | android update sdk -u -a --filter \
        tools,platform-tools,extra-android-support,extra-android-m2repository,android-24,build-tools-24.0.0
